echo "---------------------- AND ------------------ \n\n"

python3 main.py corrections/and.txt -f "DEIJOP"
echo "----"
python3 main.py corrections/and.txt -f "DEIJP"

echo "\n----------------------- OR --------------------- \n"

python3 main.py corrections/or.txt -f ""
echo "----"
python3 main.py corrections/or.txt -f "D"
echo "----"
python3 main.py corrections/or.txt -f "E"
echo "----"
python3 main.py corrections/or.txt -f "DE"

echo "\n----------------------- XOR --------------------- \n"

python3 main.py corrections/xor.txt -f ""
echo "----"
python3 main.py corrections/xor.txt -f "D"
echo "----"
python3 main.py corrections/xor.txt -f "E"
echo "----"
python3 main.py corrections/xor.txt -f "DE"

echo "\n----------------------- NOT --------------------- \n"

python3 main.py corrections/not.txt -f ""
echo "----"
python3 main.py corrections/not.txt -f "B"
echo "----" 
python3 main.py corrections/not.txt -f "C"
echo "----" 
python3 main.py corrections/not.txt -f "BC"

echo "\n----------------------- MULTIPLE --------------------- \n"

python3 main.py corrections/multiple.txt -f ""
echo "----"
python3 main.py corrections/multiple.txt -f "B"
echo "----" 
python3 main.py corrections/multiple.txt -f "C"
echo "----" 
python3 main.py corrections/multiple.txt -f "BC"

echo "\n----------------------- PARENTHESES ---------------------\n"

python3 main.py corrections/parentheses.txt -f ""
echo "---- ''"
python3 main.py corrections/parentheses.txt -f "A"
echo "---- A" 
python3 main.py corrections/parentheses.txt -f "B"
echo "---- B" 
python3 main.py corrections/parentheses.txt -f "C"
echo "---- C"
python3 main.py corrections/parentheses.txt -f "AC"
echo "---- AC" 
python3 main.py corrections/parentheses.txt -f "BC"
echo "---- BC" 
python3 main.py corrections/parentheses.txt -f "F"
echo "---- F"
python3 main.py corrections/parentheses.txt -f "G"
echo "---- G"
python3 main.py corrections/parentheses.txt -f "H"
echo "---- H" 
python3 main.py corrections/parentheses.txt -f "FH"
echo "---- FH" 
python3 main.py corrections/parentheses.txt -f "GH"